---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: renovate
  name: renovate-config
data:
  RENOVATE_AUTODISCOVER: "true"
  RENOVATE_ENDPOINT: https://gitea.lumpiasty.xyz/api/v1
  RENOVATE_PLATFORM: gitea
  RENOVATE_GIT_AUTHOR: Renovate Bot <renovate@lumpiasty.xyz>
