apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - controllers/k8up-crd-4.8.3.yaml
  - controllers/cilium.yaml
  - controllers/nginx-ingress.yaml
  - controllers/dns-public.yaml
  - controllers/cert-manager.yaml
  - controllers/cert-manager-webhook-ovh.yaml
  - controllers/openebs.yaml
  - controllers/k8up.yaml
  - controllers/external-secrets.yaml
  - controllers/vault-secrets-operator.yaml
  - controllers/mongodb-operator.yaml
  - controllers/cloudnative-pg.yaml
  - diskpools/anapistula-delrosalae-hdd.yaml
  - diskpools/anapistula-delrosalae-ssd.yaml
  - configs/bgp-cluster-config.yaml
  - configs/loadbalancer-ippool.yaml
  - configs/lvmpv-hdd-sc.yaml
  - configs/lvmpv-ssd-sc.yaml
  - configs/openbao-cert.yaml
  - configs/ovh-cert-manager-secret.yaml

  - configs/openbao-volume.yaml
  - controllers/openbao.yaml
