apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - controllers/k8up-crd-4.8.3.yaml
  - controllers/cilium.yaml
  - controllers/nginx.yaml
  - controllers/dns-public.yaml
  - controllers/cert-manager.yaml
  - controllers/openebs.yaml
  - controllers/k8up.yaml
  - diskpools/zoma-dibaiyin-hdd.yaml
  - configs/bgp-cluster-config.yaml
  - configs/loadbalancer-ippool.yaml
  - configs/cluster-issuer.yaml
  - configs/single-hdd-sc.yaml
  - configs/mayastor-snapshotclass.yaml
