apiVersion: v1
kind: ConfigMap
metadata:
  name: garm-provider-k8s-config
  namespace: garm
data:
  provider-config.yaml: |
    kubeConfigPath: ""
    runnerNamespace: "garm-runners"
    podTemplate:
      spec:
        restartPolicy: Never
    flavors:
      default:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          memory: 2Gi
