apiVersion: v1
kind: ServiceAccount
metadata:
  name: garm
  namespace: garm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: garm-provider-k8s
  namespace: garm-runners
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "configmaps", "secrets", "events"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: garm-provider-k8s
  namespace: garm-runners
subjects:
  - kind: ServiceAccount
    name: garm
    namespace: garm
roleRef:
  kind: Role
  name: garm-provider-k8s
  apiGroup: rbac.authorization.k8s.io
