---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: garm
  namespace: garm
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: garm
    serviceAccount: garm
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: garm-config
  namespace: garm
spec:
  type: kv-v2

  mount: secret
  path: garm

  destination:
    create: true
    name: garm-config
    type: Opaque
    transformation:
      excludeRaw: true

  vaultAuthRef: garm
