---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 24h
  url: https://charts.goauthentik.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2026.2.1
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: authentik
      interval: 12h
  values:
    authentik:
      postgresql:
        host: authentik-postgresql-cluster-lvmhdd-rw
        name: authentik
        user: authentik

    global:
      env:
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: authentik-secret
              key: secret_key
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-postgresql-cluster-lvmhdd-app
              key: password

    postgresql:
      enabled: false

    server:
      ingress:
        enabled: true
        ingressClassName: nginx-ingress
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - authentik.lumpiasty.xyz
        tls:
          - secretName: authentik-ingress
            hosts:
              - authentik.lumpiasty.xyz
