---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress-controller
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nginx
  namespace: nginx-ingress-controller
spec:
  interval: 24h
  url: https://helm.nginx.com/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress-controller
spec:
  interval: 30m
  chart:
    spec:
      chart: nginx-ingress
      version: 2.2.1
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: nginx-ingress-controller
      interval: 12h
  values:
    controller:
      resources:
        requests:
          cpu: 0
          memory: 128Mi
        limits:
          cpu: 100m
          memory: 128Mi

      ingressClass:
        create: true
        setAsDefaultIngress: true

      service:
        create: true
        type: LoadBalancer
        # Requirement for sharing ip with other service
        externalTrafficPolicy: Cluster
        ipFamilyPolicy: RequireDualStack
        annotations:
          # Share IP with gitea ssh so we can have the same domain for both port
          lbipam.cilium.io/sharing-key: gitea
          lbipam.cilium.io/sharing-cross-namespace: gitea
          lbipam.cilium.io/ips: 10.44.0.0,2001:470:61a3:400::1
      config:
        entries:
          proxy-buffering: "false"
