---
apiVersion: v1
kind: Namespace
metadata:
  name: openebs
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 24h
  url: https://openebs.github.io/openebs
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: openebs
      interval: 12h
  values:
    zfs-localpv:
      cidrs:
        zfsLocalPv:
          enabled: false

    lvm-localpv:
      crds:
        lmvLocalPv:
          enabled: true

    mayastor:
      csi:
        node:
          initContainers:
            # We need to disable the init container that checks for the nvme_tcp module, since Talos has that module built-in.
            # https://www.talos.dev/v1.9/kubernetes-guides/configuration/storage/#deploy-mayastor
            enabled: false
          resources:
            requests:
              cpu: 0
        controller:
          resources:
            requests:
              cpu: 0

      etcd:
        clusterDomain: homelab.lumpiasty.xyz
        # Single node cluster for now
        replicaCount: 1
      io_engine:
        # Workaround for crashing io-engine
        # https://github.com/openebs/mayastor/issues/1763#issuecomment-2481922234
        envcontext: "iova-mode=pa"
        coreList: [1, 7]
        resources:
          limits:
            cpu: 4
      agents:
        core:
          resources:
            requests:
              cpu: 0
        ha:
          node:
            resources:
              requests:
                cpu: 0
          cluster:
            resources:
              requests:
                cpu: 0
      apis:
        rest:
          resources:
            requests:
              cpu: 0
      obs:
        callhome:
          resources:
            requests:
              cpu: 0
        stats:
          resources:
            requests:
              cpu: 0

      operators:
        pool:
          resources:
            requests:
              cpu: 0

      # Remove antiaffinity, breaks when I set it to 1 replica
      nats:
        cluster:
          enable: true
          replicas: 3
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution: []

    loki:
      loki:
        commonConfig:
          replication_factor: 1
      singleBinary:
        replicas: 1
      minio:
        replicas: 1
        mode: standalone

    engines:
      local:
        lvm:
          enabled: true
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false
