apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-dns-external
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv6
  selector:
    k8s-app: kube-dns
  ports:
    - name: dns
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
