apiVersion: v1
kind: ConfigMap
metadata:
  namespace: llama
  name: llama-swap
data:
  config.yaml: |
    models:
      "DeepSeek-R1-0528-Qwen3-8B-GGUF":
        cmd: |
          /app/llama-server
          -hf unsloth/DeepSeek-R1-0528-Qwen3-8B-GGUF:Q4_K_M
          --port ${PORT}
