apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.yaml
  - auth-proxy.yaml
  - ingress.yaml
  - pvc.yaml
  - pvc-ssd.yaml
  - deployment.yaml
configMapGenerator:
  - name: llama-swap
    namespace: llama
    files:
      - config.yaml=configs/config.yaml
      - qwen_nothink_chat_template.jinja=configs/qwen_nothink_chat_template.jinja
