---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: llama-proxy
  namespace: llama
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: llama
  namespace: llama
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: llama-proxy
    serviceAccount: llama-proxy
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: llama-api-key
  namespace: llama
spec:
  type: kv-v2

  mount: secret
  path: ollama

  destination:
    create: true
    name: llama-api-key
    type: Opaque
    transformation:
      excludeRaw: true

  vaultAuthRef: llama
