---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: secustor
  namespace: immich
spec:
  interval: 24h
  url: https://secustor.dev/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: 1.0.2
      sourceRef:
        kind: HelmRepository
        name: secustor
  values:
    common:
      config:
        vecotrExtension: vectorchord
      postgres:
        host: immich-db-rw
        existingSecret:
          enabled: true
          secretName: immich-db-immich
          usernameKey: username
          passwordKey: password
      redis:
        host: redis-master
        existingSecret:
          enabled: true
          secretName: redis
          passwordKey: redis-password

    server:
      volumeMounts:
        - mountPath: /usr/src/app/upload
          name: uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: library

    machineLearning:
      enabled: true

    ingress:
      enabled: true
      className: nginx-ingress
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - host: immich.lumpiasty.xyz
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - immich.lumpiasty.xyz
          secretName: immich-ingress
