---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: searxng
  name: searxng-persistent-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: mayastor-single-ssd
