apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: teamspeak3-server
  namespace: ispeak3
spec:
  serviceName: "teamspeak3"
  replicas: 0
  selector:
    matchLabels:
      app: teamspeak3
  template:
    metadata:
      labels:
        app: teamspeak3
    spec:
      containers:
      - name: teamspeak3
        image: teamspeak:3.13.7
        ports:
        - containerPort: 9987
          name: voice
          protocol: UDP
        - containerPort: 10011
          name: query
        - containerPort: 30033
          name: filetransfer
        volumeMounts:
        - name: ts3-data
          mountPath: /var/ts3server/
      volumes:
      - name: ts3-data
        persistentVolumeClaim:
          claimName: ispeak3-ts3-data
