apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-resercher
  namespace: gpt-researcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpt-resercher
  template:
    metadata:
      labels:
        app: gpt-resercher
    spec:
      imagePullPolicy: Always
      containers:
        - name: gpt-resercher
          image: registry.lumpiasty.xyz/gpt-researcher:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "3"
              memory: "5Gi"
          env:
            - name: OPENAI_BASE_URL
              value: https://openrouter.ai/api/v1
            - name: OPENROUTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openrouter
                  key: OPENROUTER_API_KEY
            - name: OPENROUTER_LIMIT_RPS
              value: "1"

            - name: FAST_LLM
              value: openrouter:google/gemini-2.0-flash-lite-001
            - name: SMART_LLM
              value: openrouter:google/gemini-2.5-flash-preview
            - name: STRATEGIC_LLM
              value: openrouter:google/gemini-2.5-flash-preview

            - name: OLLAMA_BASE_URL
              value: "http://ollama.ollama.svc.cluster.local:11434"
            - name: EMBEDDING
              value: "ollama:nomic-embed-text"

            - name: RETRIEVER
              value: tavily
            - name: SCRAPER
              value: tavily_extract
            - name: TAVILY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: tavily
                  key: TAVILY_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: gpt-resercher-service
  namespace: gpt-researcher
spec:
  selector:
    app: gpt-resercher
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
