apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: arek.dzski@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cnameStrategy: None
          webhook:
            groupName: lumpiasty-homelab
            solverName: ovh
            config:
              endpoint: ovh-eu
              applicationKeyRef:
                name: ovh-credentials
                key: applicationKey
              applicationSecretRef:
                name: ovh-credentials
                key: applicationSecret
              consumerKeyRef:
                name: ovh-credentials
                key: consumerKey
    privateKeySecretRef:
      name: letsencrypt-key
