---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: kaneo-app-secret
  namespace: kaneo
spec:
  type: kv-v2

  mount: secret
  path: kaneo

  destination:
    create: true
    name: kaneo-app-secret
    type: Opaque
    transformation:
      excludeRaw: true
      templates:
        auth_secret:
          text: '{{ get .Secrets "auth_secret" }}'

  vaultAuthRef: kaneo
