apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - app-secret.yaml
  - oauth-secret.yaml
  - postgres-volume.yaml
  - postgres-cluster.yaml
  - release.yaml
