---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kaneo
  namespace: kaneo
spec:
  interval: 24h
  url: https://github.com/usekaneo/kaneo.git
  ref:
    tag: v2.7.7
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/    
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kaneo
  namespace: kaneo
spec:
  interval: 30m
  chart:
    spec:
      chart: ./charts/kaneo
      sourceRef:
        kind: GitRepository
        name: kaneo
  values:
    ingress:
      enabled: true
      className: nginx-ingress
      annotations:
        # nginx.ingress.kubernetes.io/rewrite-target: /$1
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - host: kaneo.lumpiasty.xyz
          paths:
            # Docs at https://github.com/usekaneo/kaneo/blob/main/charts/kaneo/README.md
            # they talk nonsense 
            - path: /
              pathType: Prefix
              service: kaneo
              port: 5173
      tls:
        - secretName: kaneo-ingress
          hosts:
            - kaneo.lumpiasty.xyz
    
    postgresql:
      enabled: false
    
    kaneo:
      image:
        tag: "2.7.3"  # renovate: depName=ghcr.io/usekaneo/kaneo registryUrl=https://ghcr.io
      env:
        clientUrl: "https://kaneo.lumpiasty.xyz"
        disablePasswordRegistration: true
        database:
          external:
            enabled: true
            existingSecret:
              enabled: true
              name: kaneo-db-app
              passwordKey: uri
      extraEnv:
        - name: CUSTOM_OAUTH_DISCOVERY_URL
          value: https://authentik.lumpiasty.xyz/application/o/kaneo/.well-known/openid-configuration
        - name: CUSTOM_OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: kaneo-authentik
              key: client_id
        - name: CUSTOM_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: kaneo-authentik
              key: client_secret
        - name: DISABLE_GUEST_ACCESS
          value: "true"
