apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-data
  namespace: nas
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: mayastor-single-hdd
