---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ollama-proxy
  namespace: ollama
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: ollama
  namespace: ollama
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: ollama-proxy
    serviceAccount: ollama-proxy
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ollama-api-key
  namespace: ollama
spec:
  type: kv-v2

  mount: secret
  path: ollama

  destination:
    create: true
    name: ollama-api-key
    type: Opaque
    transformation:
      excludeRaw: true

  vaultAuthRef: ollama
