# Would never work without this awesome blogpost
# https://farcaller.net/2024/making-cilium-bgp-work-with-ipv6/

log "/tmp/bird.log" all;
log syslog all;

#Router ID
router id 192.168.1.1;

protocol kernel kernel4 {
    learn;
    scan time 10;
    merge paths yes;
    ipv4 {
        # Importing only default route, we're their default gateway so they dont need rest
        import filter { if net = 0.0.0.0/0 then { igp_metric = 100; accept; } reject; };
        export all;
    };
}

protocol kernel kernel6 {
    learn;
    scan time 10;
    merge paths yes;
    ipv6 {
        import filter { if net = ::/0 then { igp_metric = 100; accept; } reject; };
        export all;
    };
}

protocol device {
    scan time 10;
}

protocol direct {
    interface "*";
}

protocol bgp homelab {
    debug { events };
    passive;
    direct;
    local 2001:470:61a3:100:ffff:ffff:ffff:ffff as 65000;
    neighbor range 2001:470:61a3:100::/64 as 65000;
    ipv4 {
        extended next hop yes;
        import all;
        export all;
    };
    ipv6 {
        import all;
        export all;
    };
}
