zfs-localpv:
  cidrs:
    zfsLocalPv:
      enabled: false

lvm-localpv:
  crds:
    lmvLocalPv:
      enabled: false

mayastor:
  csi:
    node:
      initContainers:
        # We need to disable the init container that checks for the nvme_tcp module, since Talos has that module built-in.
        # https://www.talos.dev/v1.9/kubernetes-guides/configuration/storage/#deploy-mayastor
        enabled: false
  etcd:
    clusterDomain: homelab.lumpiasty.xyz
    # Single node cluster for now
    replicaCount: 1
  io_engine:
    # Workaround for crashing io-engine
    # https://github.com/openebs/mayastor/issues/1763#issuecomment-2481922234
    envcontext: "iova-mode=pa"

engines:
  local:
    lvm:
      enabled: false
    zfs:
      enabled: false
  replicated:
    mayastor:
      enabled: true
