apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: blakeblackshear
  namespace: frigate
spec:
  interval: 24h
  url: https://blakeblackshear.github.io/blakeshome-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: frigate
spec:
  interval: 30m
  chart:
    spec:
      chart: frigate
      version: 7.8.0
      sourceRef:
        kind: HelmRepository
        name: blakeblackshear
        namespace: frigate
      interval: 12h
  values:
    config: |
      mqtt:
        enabled: False

      tls:
        enabled: False

      auth:
        enabled: True
        cookie_secure: True

      record:
        enabled: True
        retain:
          days: 90
          mode: motion

      objects:
        track:
          - person
          - bicycle
          - car
          - motorcycle
          - cat
          - dog
          - horse
          - sheep
          - cow
          - bear

      review:
        alerts:
          labels:
            - person
            - bicycle
            - car
            - motorcycle
            - cat
            - dog
            - horse
            - sheep
            - cow
            - bear

      cameras:
        dom:
          enabled: True
          ffmpeg:
            inputs:
              - path: rtsp://127.0.0.1:8554/dom
                roles:
                  - audio
                  - detect
                  - record
            output_args:
              record: preset-record-generic-audio-copy
          motion:
            mask:
              # Sasiad
              - 0.436,0,0.421,0.072,0.424,0.124,0.304,0.242,0.295,0.194,0.035,0.497,0.035,0.6,0,0.664,0,0
        garaz:
          enabled: True
          ffmpeg:
            inputs:
              - path: rtsp://127.0.0.1:8554/garaz
                roles:
                  - audio
                  - detect
                  - record
            output_args:
              record: preset-record-generic-audio-copy
          motion:
            mask:
              # Sasiad
              - 0.662,0.212,0.569,0.2,0.566,0.149,0.549,0.119,0.532,0.169,0.495,0.14,0.491,0,0.881,0,1,0.154,1,0.221,0.986,0.296,0.94,0.28,0.944,0.178,0.664,0.126
              # Drzewo
              - 0.087,0.032,0,0.174,0,0.508,0.139,0.226,0.12,0.108
          objects:
            filters:
              person:
                # Uparty false positive
                mask: 0.739,0.725,0.856,0.76,0.862,0.659,0.746,0.614

      ffmpeg:
        hwaccel_args: preset-vaapi

      detectors:
        ov_0:
          type: openvino
          device: CPU
      model:
        width: 300
        height: 300
        input_tensor: nhwc
        input_pixel_format: bgr
        path: /openvino-model/ssdlite_mobilenet_v2.xml
        labelmap_path: /openvino-model/coco_91cl_bkgr.txt

      go2rtc:
        streams:
          dom:
            - rtsp://{FRIGATE_RTSP_DOM_USER}:{FRIGATE_RTSP_DOM_PASSWORD_URLENCODED}@192.168.3.10:554/Streaming/Channels/101
          garaz:
            - rtsp://{FRIGATE_RTSP_GARAZ_USER}:{FRIGATE_RTSP_GARAZ_PASSWORD_URLENCODED}@192.168.3.11:554/Streaming/Channels/101
        webrtc:
          candidates:
            - frigate-rtc.lumpiasty.xyz:8555
    persistence:
      media:
        enabled: true
        size: 500Gi
        storageClass: mayastor-single-hdd
        skipuninstall: true
      config:
        enabled: true
        size: 1Gi
        storageClass: mayastor-single-hdd
        skipuninstall: true
    envFromSecrets:
      - frigate-camera-rtsp

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.org/websocket-services: frigate
      hosts:
        - host: frigate.lumpiasty.xyz
          paths:
            - path: /
              portName: http-auth
      tls:
        - hosts:
            - frigate.lumpiasty.xyz
          secretName: frigate-ingress

    nodeSelector:
      kubernetes.io/hostname: anapistula-delrosalae

    # GPU access
    extraVolumes:
      - name: dri
        hostPath:
          path: /dev/dri/renderD128
          type: CharDevice

    extraVolumeMounts:
      - name: dri
        mountPath: /dev/dri/renderD128

    securityContext:
      # Not ideal
      privileged: true
