apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: blakeblackshear
  namespace: frigate
spec:
  interval: 24h
  url: https://blakeblackshear.github.io/blakeshome-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: frigate
spec:
  interval: 30m
  chart:
    spec:
      chart: frigate
      version: 7.8.0
      sourceRef:
        kind: HelmRepository
        name: blakeblackshear
        namespace: frigate
      interval: 12h
  values:
    config: |
      mqtt:
        enabled: False

      tls:
        enabled: False

      auth:
        enabled: True
        cookie_secure: True

      record:
        enabled: True
        retain:
          days: 90
          mode: motion

      cameras:
        dom:
          enabled: True
          ffmpeg:
            inputs:
              - path: rtsp://{FRIGATE_RTSP_DOM_USER}:{FRIGATE_RTSP_DOM_PASSWORD}@192.168.3.10:554/Streaming/Channels/101
                roles:
                  - audio
                  - detect
                  - record
        garaz:
          enabled: True
          ffmpeg:
            inputs:
              - path: rtsp://{FRIGATE_RTSP_GARAZ_USER}:{FRIGATE_RTSP_GARAZ_PASSWORD}@192.168.3.11:554/Streaming/Channels/101
                roles:
                  - audio
                  - detect
                  - record
    persistence:
      media:
        enabled: true
        size: 100Gi
        storageClass: mayastor-single-hdd
        skipuninstall: true
      config:
        enabled: true
        size: 100Mi
        storageClass: mayastor-single-hdd
        skipuninstall: true
    envFromSecrets:
      - frigate-camera-rtsp

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - host: frigate.lumpiasty.xyz
          paths:
            - path: /
              portName: http-auth
      tls:
        - hosts:
            - frigate.lumpiasty.xyz
          secretName: frigate-ingress
