---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: camera
  namespace: frigate
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: camera
  namespace: frigate
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: frigate-camera
    serviceAccount: camera
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: frigate-camera-rtsp
  namespace: frigate
spec:
  type: kv-v2

  mount: secret
  path: cameras

  destination:
    create: true
    name: frigate-camera-rtsp
    type: Opaque
    transformation:
      excludeRaw: true
      templates:
        FRIGATE_RTSP_DOM_PASSWORD_URLENCODED:
          text: '{{ urlquery (get .Secrets "FRIGATE_RTSP_DOM_PASSWORD") }}'
        FRIGATE_RTSP_GARAZ_PASSWORD_URLENCODED:
          text: '{{ urlquery (get .Secrets "FRIGATE_RTSP_GARAZ_PASSWORD") }}'

  vaultAuthRef: camera
