apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crawl4ai
  - crawl4ai-proxy
  - authentik
  - gitea
  - frigate
  - llama
  - immich
  - nas
  - ispeak3
  - openwebui
  - woodpecker
