---
- name: Configure container runtime defaults
  community.routeros.api_find_and_modify:
    ignore_dynamic: false
    path: container config
    find: {}
    values:
      tmpdir: tmp

- name: Configure container env lists
  community.routeros.api_modify:
    path: container envs
    data: []
    handle_absent_entries: remove
    handle_entries_content: remove_as_much_as_possible

- name: Configure container mounts
  community.routeros.api_modify:
    path: container mounts
    data:
      - dst: /var/lib/tailscale
        list: tailscale_state
        src: tailscale/state
    handle_absent_entries: remove
    handle_entries_content: remove_as_much_as_possible

- name: Configure tailscale container
  community.routeros.api_modify:
    path: container
    data:
      - dns: 172.17.0.1
        interface: veth-tailscale
        logging: true
        mountlists: tailscale_state
        name: tailscale
        remote-image: gitea.lumpiasty.xyz/lumpiasty/mikrotik-tailscale:stable
        root-dir: tailscale/root
        start-on-boot: true
    handle_absent_entries: remove
    handle_entries_content: remove_as_much_as_possible
