---
apiVersion: local.openebs.io/v1alpha1
kind: LVMVolume
metadata:
  labels:
    kubernetes.io/nodename: anapistula-delrosalae
  name: meridian-data-lvmssd
  namespace: openebs
spec:
  capacity: "1048576000"
  ownerNodeID: anapistula-delrosalae
  shared: "yes"
  thinProvision: "no"
  vgPattern: ^openebs-ssd$
  volGroup: openebs-ssd
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: meridian-data-lvmssd
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ssd-lvmpv
  volumeMode: Filesystem
  csi:
    driver: local.csi.openebs.io
    fsType: btrfs
    volumeHandle: meridian-data-lvmssd
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: meridian-data-lvmssd
  namespace: meridian
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ssd-lvmpv
  volumeName: meridian-data-lvmssd
