when:
  - event: push
    path:
      include:
        - mikrotik/coredns/**
        - docker/**

steps:
  - name: Get registry creds from OpenBao
    image: quay.io/openbao/openbao:2.5.5
    environment:
      VAULT_ADDR: https://openbao.lumpiasty.xyz:8200
      ROLE_ID:
        from_secret: renovate_role_id
      SECRET_ID:
        from_secret: renovate_secret_id
    commands:
      - bao write -field token auth/approle/login
          role_id=$ROLE_ID
          secret_id=$SECRET_ID > /woodpecker/.vault_id
      - export VAULT_TOKEN=$(cat /woodpecker/.vault_id)
      - 'printf "PLUGIN_USERNAME=%s\n" "$(bao kv get -mount secret -field REGISTRY_USERNAME container-registry)" > /woodpecker/registry.env'
      - 'printf "PLUGIN_PASSWORD=%s\n" "$(bao kv get -mount secret -field REGISTRY_PASSWORD container-registry)" >> /woodpecker/registry.env'

  - name: Build and push mikrotik coredns
    image: woodpeckerci/plugin-docker-buildx:6.1.1
    privileged: true
    settings:
      registry: gitea.lumpiasty.xyz
      repo: gitea.lumpiasty.xyz/lumpiasty/coredns-mikrotik
      platforms: linux/arm64
      tags:
        - latest
        - ${CI_COMMIT_SHA:0:8}
      dockerfile: mikrotik/coredns/Dockerfile
      context: mikrotik/coredns/
      env_file: /woodpecker/registry.env
      cache_images:
        - gitea.lumpiasty.xyz/lumpiasty/coredns-mikrotik:buildcache
    depends_on: ["Get registry creds from OpenBao"]

  - name: Build and push llama-swap-supervisord
    image: woodpeckerci/plugin-docker-buildx:6.1.1
    privileged: true
    settings:
      registry: gitea.lumpiasty.xyz
      repo: gitea.lumpiasty.xyz/lumpiasty/supervisord
      platforms: linux/arm64
      tags:
        - latest
        - ${CI_COMMIT_SHA:0:8}
      dockerfile: docker/supervisord/Dockerfile
      context: docker/supervisord/
      env_file: /woodpecker/registry.env
      cache_images:
        - gitea.lumpiasty.xyz/lumpiasty/supervisord:buildcache
    depends_on: ["Get registry creds from OpenBao"]

  - name: Invalidate OpenBao token
    image: quay.io/openbao/openbao:2.5.5
    environment:
      VAULT_ADDR: https://openbao.lumpiasty.xyz:8200
    commands:
      - export VAULT_TOKEN=$(cat /woodpecker/.vault_id)
      - bao write -f auth/token/revoke-self
    when:
      - status: [success, failure]
    depends_on:
      - Build and push mikrotik coredns
      - Build and push llama-swap-supervisord
