---
- name: Install bird2
  opkg:
    name: "{{ item }}"
    state: present
  # Workaround for opkg module not handling multiple names at once well
  loop:
    - bird2
    - bird2c

- name: Set up bird.conf
  ansible.builtin.copy:
    src: bird.conf
    dest: /etc/bird.conf
    mode: "644"
  notify: Reload bird
