apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gitea-charts
  namespace: gitea
spec:
  interval: 24h
  url: https://dl.gitea.com/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  interval: 30m
  chart:
    spec:
      chart: gitea
      version: 12.1.2
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: gitea
      interval: 12h
  values:
    postgresql-ha:
      enabled: false

    postgresql:
      enabled: false
      primary:
        persistence:
          enabled: true
          storageClass: mayastor-single-hdd
        resources:
          requests:
            cpu: 0

    valkey-cluster:
      enabled: false

    valkey:
      enabled: true
      primary:
        persistence:
          enabled: true
          storageClass: mayastor-single-hdd
        resources:
          requests:
            cpu: 0

    persistence:
      enabled: true
      storageClass: mayastor-single-hdd

    gitea:
      additionalConfigFromEnvs:
        - name: GITEA__DATABASE__PASSWD
          valueFrom:
            secretKeyRef:
              name: gitea-postgresql-cluster-app
              key: password
      config:
        database:
          DB_TYPE: postgres
          HOST: gitea-postgresql-cluster-rw:5432
          NAME: app
          USER: app
        indexer:
          ISSUE_INDEXER_TYPE: bleve
          REPO_INDEXER_ENABLED: true
      admin:
        username: GiteaAdmin
        email: gi@tea.com
        passwordMode: initialOnlyRequireReset

    service:
      ssh:
        annotations:
          lbipam.cilium.io/sharing-key: gitea
          lbipam.cilium.io/sharing-cross-namespace: nginx-ingress
          lbipam.cilium.io/ips: 10.44.0.6,2001:470:61a3:400::6
        type: LoadBalancer
        port: 22
        # Requirement for sharing ip with other service
        externalTrafficPolicy: Cluster
        ipFamilyPolicy: RequireDualStack

    ingress:
      enabled: true
      className: nginx-ingress
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        acme.cert-manager.io/http01-edit-in-place: "true"
      hosts:
        - host: gitea.lumpiasty.xyz
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - gitea.lumpiasty.xyz
          secretName: gitea-ingress

    resources:
      requests:
        cpu: 0

    initContainers:
      resources:
        requests:
          cpu: 0
