---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup
  namespace: gitea
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: backup
  namespace: gitea
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: backup
    serviceAccount: backup
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gitea-backup-restic
  namespace: gitea
spec:
  type: kv-v2

  mount: secret
  path: restic

  destination:
    create: true
    name: gitea-backup-restic
    type: Opaque
    transformation:
      excludeRaw: true

  vaultAuthRef: backup
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gitea-backup-backblaze
  namespace: gitea
spec:
  type: kv-v2

  mount: secret
  path: backblaze

  destination:
    create: true
    name: gitea-backup-backblaze
    type: Opaque
    transformation:
      excludeRaw: true

  vaultAuthRef: backup
